<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    const REFUND_STATUS_PENDING = 'pending';
    const REFUND_STATUS_APPLIED = 'applied';
    const REFUND_STATUS_PROCESSING = 'processing';
    const REFUND_STATUS_SUCCESS = 'success';
    const REFUND_STATUS_FAILED = 'failed';

    const SHIP_STATUS_PENDING = 'pending';
    const SHIP_STATUS_DELIVERED = 'delivered';
    const SHIP_STATUS_RECEIVED = 'received';

    public static $refundStatusMap = [
        self::REFUND_STATUS_PENDING => '未退款',
        self::REFUND_STATUS_APPLIED => '已申请退款',
        self::REFUND_STATUS_PROCESSING => '退款中',
        self::REFUND_STATUS_SUCCESS => '退款成功',
        self::REFUND_STATUS_FAILED => '退款失败',
    ];

    public static $shipStatusMap = [
        self::SHIP_STATUS_PENDING => '未发货',
        self::SHIP_STATUS_DELIVERED => '已发货',
        self::SHIP_STATUS_RECEIVED => '已收货',
    ];

    protected $fillable = [
        'no',
        'address',
        'total_amount',
        'remark',
        'paid_at',
        'payment_method',
        'payment_no',
        'refund_status',
        'refund_no',
        'closed',
        'reviewed',
        'ship_status',
        'ship_data',
        'extra',
    ];

    protected $casts = [
        'closed' => 'boolean',
        'reviewed' => 'boolean',
        'address' => 'json',
        'ship_data' => 'json',
        'extra' => 'json',
    ];

    protected $dates = [
        'paid_at',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    /**
     *  事件监听
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function ($model) {
            // 如果不存在订单流水号
            if (!$model->no) {
                // 就生成一个
                $model->no = static::findAvailableNo();
                // 如果生成失败了，则终止订单的创建
                if (!$model->no) {
                    return false;
                }
            }
        });
    }

    /**
     *  生成一个随机的且在数据库中唯一的订单流水号
     * @return bool|string
     * @throws \Exception
     */
    public static function findAvailableNo()
    {
        // 以当前日期时间生成一个前缀
        $prefix = date('YmdHis');

        for ($i = 0; $i < 10; $i++) {
            // 随机生成一个6位数字
            $no = $prefix . str_pad(random_int(0, 999999), 6, 0, STR_PAD_LEFT);
            // 判断当前订单号是否存在
            if (!static::query()->where('no', $no)->exists()) {
                return $no;
            }
        }

        \Log::waring('find order no failed');

        return false;
    }
}
